import { useState } from "react";
import { returnAllActive } from "../util";
import PlayerCard from "../PlayerCard/PlayerCard";
import {getDocs, collection, query, where} from "firebase/firestore"


import "./Store.css"
import { db } from "../../db/firebase";

function Store() {
    const [openedPlayers, setOpenedPlayers] = useState([]);

    function getRandomInt(min, max) {
        var range = max - min + 1;
        var byteArrayLength = Math.ceil(Math.log2(range) / 8); // Calculate the number of bytes needed based on the range
        
        var byteArray = new Uint8Array(byteArrayLength);
        window.crypto.getRandomValues(byteArray);
      
        var maxRange = Math.pow(256, byteArrayLength); // Calculate the maximum possible value from the generated bytes
        
        if (byteArray[0] >= Math.floor(maxRange / range) * range) {
          return getRandomInt(min, max); // If the generated value is outside the desired range, recursively call the function again
        }
        
        var randomValue = 0;
        for (var i = 0; i < byteArrayLength; i++) {
          randomValue += byteArray[i] * Math.pow(256, i); // Calculate the random value by combining the generated bytes
        }
        
        return min + (randomValue % range);
    }
          
    async function openPack(packLength) {
        console.log(returnAllActive());
        const players = await getDocs(collection(db, "players"));
        var allPlayers = [];
        players.forEach(doc => {
            var player = doc.data();
            player.id = doc.id;
            allPlayers.push(player);
        })
        console.log(allPlayers);
        // var allActive = returnAllActive();
        var packedPlayers = [];
        for(var i = 0; i < packLength; i++) {
            let random = getRandomInt(0, allPlayers.length);
            packedPlayers.push(allPlayers[random]);
        }
        console.log(packedPlayers);
        setOpenedPlayers(packedPlayers);
    }
    
    return(
        <div>
            <button onClick={openPack}>Open Pack</button>
            {openedPlayers.length > 0 && <div className="openedPlayers">
                {openedPlayers.map(player => (
                    <div className="playerCardContainer">
                        <PlayerCard player={player} team={player.team} />
                    </div>
                ))}
            </div>}
        </div>
    )
}

export default Store;